apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-app
spec:
   replicas: 1
   selector:
     matchlabels:
       app: hospital
   template:
     metadata:
       labels:
         app: hospital 
     spec:
       containers:
       - name: hospital

       image: abhishekjoshhi/hospital-app:v1.0.0
       ports:
       - containerPort: 5000
       envFrom:
       - configMapRef:
           name: hospital-config 
       - secretRef:
           name: hospital-secret 