apiVersion: v1
kind: Service 
metadata:
  name: {{ .Values.service.name }}  
spec:
  selector:
    app: hospital 
  port:
  - port: {{.Values.sevice.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}